<a href="https://colab.research.google.com/github/spacemaninSeoul/justpractice/blob/main/%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_%EA%B8%B0%EC%B4%88_%EC%A0%95%EB%A6%AC_%EB%B0%8F_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 텐서플로 기초 정리

In [1]:
import tensorflow as tf

기본 텐서 만들기. 그냥 숫자, 리스트 담는 곳이다.

In [2]:
ten = tf.constant(3)

In [3]:
print(ten)

tf.Tensor(3, shape=(), dtype=int32)


텐서가 필요한 이유

딥러닝을 할 때 많은 연산을 하게 됨. 연산을 간단하게 만들어주는 행렬과 비슷한 역할을 함.
 - 행렬로 인풋 /w값 저장가능
 - 그럼 node 값 계산식이 쉬워진다.

In [4]:
텐서 = tf.constant( [3, 4, 5])
텐서2 = tf.constant( [6, 7, 8])
print(텐서+텐서2)

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


In [5]:
# 텐서로 행렬 표현
텐서3 = tf.constant( [[1, 2],
                    [3, 4]])

In [6]:
print(tf.add(텐서, 텐서2))

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


텐서 연산들
기본적으로 사칙연산 기호를 사용해도 됨.
 - tf.add()
 - tf.subtract()
 - tf.divide()
 - tf.multiply()
 - tf.matmul() 행렬곱

In [9]:
# tf.zeros() : 0만 담긴 텐서 만들어줌
텐서4 = tf.zeros( [2,2])
print(텐서4)
tf5 = tf.zeros( [2,2,3])
print(tf5)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)


In [13]:
# tensor의 shape
print(텐서4.shape)
print(tf5.shape)

(2, 2)
(2, 2, 3)


In [14]:
#tensor의 datatype
텐서 = tf.constant( [3, 4, 5], tf.float32)
print(텐서)

tf.Tensor([3. 4. 5.], shape=(3,), dtype=float32)


In [17]:
# weight 저장하고 싶으면 Variable변수 만들기
w = tf.Variable(1.0)
print(w)
print(w.numpy())

# 변수 변경
w.assign(2)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
1.0
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>


# 2. 딥러닝으로 풀어보는 수학문제(Linear Regression)

In [18]:
키 = 170
신발 = 260

In [19]:
#신발 = 키 * a + b

NameError: ignored

In [20]:
a = tf.Variable(0.1)
b = tf.Variable(0.2)

In [21]:
# a, b 경사하강법으로 구하기
opt = tf.keras.optimizers.Adam(learning_rate=0.1) # gradient를 알아서 스마트하게 바꿔줌

In [ ]:
# opt.minimize(손실함수, var_list=[a, b])  var_list : 경사하강법으로 업데이트할 weight Variable 목록

In [22]:
def 손실함수():
  예측값 = 키 * a + b
  return tf.square(260 - 예측값)

In [23]:
opt.minimize(손실함수, var_list=[a, b]) # 경사하강 1번 해줌

<tf.Variable 'UnreadVariable' shape=() dtype=int64, numpy=1>

In [24]:
for i in range(300):
  opt.minimize(손실함수, var_list=[a, b])

In [26]:
print(a.numpy(), b.numpy())

1.5198832 1.6198832


# 3. 대학원 합격 예측 AI 만들기



In [28]:
import tensorflow as tf

In [29]:
# 1. 딥러닝 model 디자인하기
# Sequential 쓰면 신경망 레이어들 쉽게 만들어줌. Dense() 히든레이어에서의 노드 개수. 마지막 레이어는 하나의 결과를 가져야하기에 (1). 확률 한 개를 예측할 때도 1개
# 레이어에 activation functuin 넣기 (sigmoid, tanh, relu, softmax, leakyRelu)
# 마지막 레이어는 예측결과를 뱉어야 (0~1 사이의 확률)
model = tf.keras.models.Sequential([
                          tf.keras.layers.Dense(64, activation= 'tanh'),
                          tf.keras.layers.Dense(128, activation= 'tanh'),
                          tf.keras.layers.Dense(1, activation= 'sigmoid') # 0~1 사이의 확률을 뱉고싶으면 sigmoid
])

In [30]:
# 2. model compile 하기
# optimizer는 w1 <= w1 - (å * ∂E/∂w1  <- 이 값을 알맞게 조정해줌)
# 0과 1 사이에서의 확률, 분류 문제를 예측할때 로스 함수는 binary_crossentropy를 쓸 수 있다.
model.compile(optimizer='adam' , loss='binary_crossentropy' , metrics=['accuracy'])

In [31]:
import pandas as pd

In [33]:
data = pd.read_csv('/content/gpascore.csv')
print(data)

     admit    gre   gpa  rank
0        0  380.0  3.21     3
1        1  660.0  3.67     3
2        1  800.0  4.00     1
3        1  640.0  3.19     4
4        0  520.0  2.33     4
..     ...    ...   ...   ...
421      1  750.0  3.44     4
422      1  710.0  3.66     4
423      0  450.0  3.25     4
424      1  760.0  3.76     2
425      1  710.0  3.82     3

[426 rows x 4 columns]


In [34]:
data.isnull().sum()

admit    0
gre      1
gpa      0
rank     0
dtype: int64

In [35]:
data= data.dropna()

In [36]:
# y 입력값 만들기 (일명 label). y = [정답1, 정답2, 정답3 ...] 이렇게 만들어야
y데이터 = data['admit'].values
y데이터

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,

In [39]:
x데이터 = []
for i, rows in data.iterrows(): #iterrow() <- data라는 데이터프레임을 가로 한 줄씩 출력해주는 함수
  x데이터.append([rows['gre'], rows['gpa'], rows['rank']])

In [40]:
print(x데이터)

[[380.0, 3.21, 3.0], [660.0, 3.67, 3.0], [800.0, 4.0, 1.0], [640.0, 3.19, 4.0], [520.0, 2.33, 4.0], [760.0, 3.0, 2.0], [560.0, 2.98, 1.0], [400.0, 3.08, 2.0], [540.0, 3.39, 3.0], [700.0, 3.92, 2.0], [750.0, 3.6, 4.0], [440.0, 3.22, 1.0], [760.0, 4.0, 1.0], [600.0, 3.08, 2.0], [700.0, 4.0, 1.0], [480.0, 3.44, 3.0], [490.0, 3.87, 4.0], [360.0, 2.56, 3.0], [800.0, 3.75, 2.0], [500.0, 3.17, 3.0], [660.0, 3.63, 2.0], [600.0, 2.82, 4.0], [680.0, 3.19, 4.0], [760.0, 3.35, 2.0], [800.0, 3.66, 1.0], [620.0, 3.61, 1.0], [520.0, 3.74, 4.0], [780.0, 3.22, 2.0], [520.0, 3.29, 1.0], [540.0, 3.78, 4.0], [760.0, 3.35, 3.0], [600.0, 3.4, 3.0], [800.0, 4.0, 3.0], [360.0, 3.14, 1.0], [400.0, 3.05, 2.0], [580.0, 3.25, 1.0], [520.0, 2.9, 3.0], [500.0, 3.13, 2.0], [520.0, 2.68, 3.0], [560.0, 2.42, 2.0], [580.0, 3.32, 2.0], [600.0, 3.15, 2.0], [500.0, 3.31, 3.0], [700.0, 2.94, 2.0], [460.0, 3.45, 3.0], [580.0, 3.46, 2.0], [500.0, 2.97, 4.0], [440.0, 2.48, 4.0], [400.0, 3.35, 3.0], [640.0, 3.86, 3.0], [440.0,

In [41]:
import numpy as np

In [43]:
model.fit(np.array(x데이터), np.array(y데이터), epochs=1000) # list 그대로 넣을 순 없고, numpy array 나 tf tensor를 넣어야

Epoch 1/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.6997 - accuracy: 0.4918
Epoch 2/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.7095 - accuracy: 0.4729
Epoch 3/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.6928 - accuracy: 0.5388
Epoch 4/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.6936 - accuracy: 0.5294
Epoch 5/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.6901 - accuracy: 0.5294
Epoch 6/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6952 - accuracy: 0.4871
Epoch 7/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6949 - accuracy: 0.5059
Epoch 8/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.6908 - accuracy: 0.5388
Epoch 9/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.6829 - accuracy: 0.5953
Epoch 10/1000
14/14 [==============================] - 0s 3ms/step - loss: 0.6992 - accuracy: 0.4988

In [44]:
# 예측
예측값 = model.predict( [ [750, 3.70, 3], [400, 2.2, 1]])
print(예측값)

[[0.60034287]
 [0.01787549]]
